services:
  db:
    image: mysql:8.0
    container_name: testcontainers_api_db
    environment:
      DATABASE_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_development
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  api:
    build:
      context: .
    container_name: testcontainers_api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
volumes:
  db_data:
