name: E2E
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./e2e
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: e2e/package-lock.json
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npm test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: ./screenshots/
          retention-days: 30