name: E2E
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./e2e
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "npm"
      - run: npm ci
      - run: npm test
